const pt = {
  "Product":"Produto","Architecture":"Arquitetura","Roadmap":"Roadmap","Install":"Instalar","View on GitHub":"Ver no GitHub",
  "v0.3.1 · now available through APT":"v0.3.1 · disponível via APT","Open source · Rust native · Linux first":"Código aberto · Rust nativo · Feito para Linux",
  "Your Linux fleet,":"Sua frota Linux,","inside the terminal.":"dentro do terminal.","Monitor every machine, organize the noise, and stay close to the systems you run without leaving your keyboard.":"Monitore cada máquina, organize o ruído e fique perto dos sistemas que você administra sem tirar as mãos do teclado.",
  "Install nekoHub":"Instalar nekoHub","01 / Why nekoHub":"01 / Por que nekoHub","Fleet visibility should feel":"Visibilidade da frota deve parecer","instant":"instantânea","not like another platform to operate.":"não outra plataforma para administrar.",
  "nekoHub keeps the experience local, tactile, and fast. One terminal becomes the calm surface between you and every Linux machine you care about.":"nekoHub mantém a experiência local, tátil e rápida. Um terminal vira a superfície tranquila entre você e cada máquina Linux importante.",
  "Built for the command line":"Feito para a linha de comando","Native signals.":"Sinais nativos.","No dashboard tax.":"Sem imposto de dashboard.","The nekoHub agent reads Linux directly. Metrics stay lightweight, structured, and available without a permanent SSH polling loop.":"O agente nekoHub lê o Linux diretamente. As métricas continuam leves, estruturadas e disponíveis sem consultas permanentes por SSH.",
  "Linux-native telemetry":"Telemetria nativa do Linux","Direct reads from":"Leituras diretas de","keep the agent transparent and efficient.":"mantêm o agente transparente e eficiente.","Local by default":"Local por padrão","A Unix socket keeps host communication close, predictable, and easy to reason about.":"Um socket Unix mantém a comunicação próxima, previsível e fácil de entender.","Prometheus ready":"Pronto para Prometheus","Use nekoHub's focused TUI and keep the monitoring stack you already trust.":"Use a TUI focada do nekoHub e mantenha a stack de monitoramento em que você já confia.",
  "A cleaner control loop":"Um ciclo de controle mais limpo","SSH opens the door.":"SSH abre a porta.","The agent keeps watch.":"O agente mantém a vigilância.","Discovery and operations still use SSH. Continuous metrics come from a purpose-built agent, so collection remains stable without holding remote sessions open.":"Descoberta e operações ainda usam SSH. Métricas contínuas vêm de um agente dedicado, mantendo a coleta estável sem sessões remotas abertas.",
  "YOU":"VOCÊ","one keyboard-first workspace":"um workspace feito para o teclado","SSH · DISCOVER + OPERATE":"SSH · DESCOBRIR + OPERAR","HOST":"HOST","native Linux telemetry":"telemetria nativa do Linux","METRICS · CONTINUOUS":"MÉTRICAS · CONTÍNUAS","EXPORT":"EXPORTAR","optional, always compatible":"opcional, sempre compatível",
  "Now and next":"Agora e depois","Useful today.":"Útil hoje.","Built for the long run.":"Feito para o longo prazo.","CURRENT · v0.3.1":"ATUAL · v0.3.1","Shipping now":"Disponível agora","On the horizon":"No horizonte",
  "Local host monitoring":"Monitoramento local","Machine inventory":"Inventário de máquinas","Persistent groups":"Grupos persistentes","Prometheus metrics":"Métricas Prometheus","Native /proc and /sys reads":"Leitura nativa de /proc e /sys","APT installation":"Instalação via APT","Secure remote agent pairing":"Pareamento seguro de agentes","Docker and Podman":"Docker e Podman","Services and logs":"Serviços e logs","Custom themes":"Temas personalizados","Community theme store":"Loja de temas da comunidade",
  "Made for people who run things":"Feito para quem mantém tudo funcionando","From one quiet homelab to a fleet of restless VPSs.":"De um homelab tranquilo a uma frota de VPS inquietas.","Sysadmins":"Sysadmins","See every host without leaving the terminal.":"Veja cada host sem sair do terminal.","Homelabbers":"Homelabbers","Keep the lab organized, legible, and fun.":"Mantenha o lab organizado, legível e divertido.","Inspect faster and stay compatible with existing observability.":"Investigue mais rápido sem abandonar sua observabilidade atual.","Terminal people":"Pessoas de terminal","Use an interface that respects your keyboard and attention.":"Use uma interface que respeita seu teclado e sua atenção.",
  "Up and running":"Pronto para rodar","One command.":"Um comando.","Your fleet, in view.":"Sua frota à vista.","Install the current release from the official APT repository. nekoHub is open source and built in public.":"Instale a versão atual pelo repositório APT oficial. nekoHub é código aberto e desenvolvido em público.","APT repository":"Repositório APT","Read the source":"Ler o código","Copy":"Copiar","Copied":"Copiado","Linux fleet management,":"Gestão de frotas Linux,","designed for the terminal.":"feita para o terminal.","Star on GitHub":"Dar estrela no GitHub","Back to top ↑":"Voltar ao topo ↑",
  "Personalize your terminal":"Personalize seu terminal","A theme shop,":"Uma loja de temas,","made by the community.":"feita pela comunidade.","Discover palettes crafted for long sessions, share your own, and make every fleet feel like home.":"Descubra paletas criadas para longas sessões, compartilhe as suas e faça cada frota ter a sua cara.","COMING SOON":"EM BREVE","THEME PREVIEW":"PRÉVIA DE TEMA"
};

const ja = {
  "Product":"プロダクト","Architecture":"構成","Roadmap":"ロードマップ","Install":"インストール","View on GitHub":"GitHubで見る",
  "v0.3.1 · now available through APT":"v0.3.1 · APTで配布中","Open source · Rust native · Linux first":"オープンソース · Rustネイティブ · Linuxファースト","Your Linux fleet,":"Linuxフリートを、","inside the terminal.":"ターミナルの中に。","Monitor every machine, organize the noise, and stay close to the systems you run without leaving your keyboard.":"すべてのマシンを監視し、情報を整理し、キーボードから手を離さずにシステムを管理できます。","Install nekoHub":"nekoHubをインストール",
  "01 / Why nekoHub":"01 / nekoHubを選ぶ理由","Fleet visibility should feel":"フリートの可視化は","instant":"瞬時","not like another platform to operate.":"であるべきです。","nekoHub keeps the experience local, tactile, and fast. One terminal becomes the calm surface between you and every Linux machine you care about.":"nekoHubはローカルで、直感的で、高速。ひとつのターミナルが大切なLinuxマシンをつなぐ静かな操作面になります。",
  "Built for the command line":"コマンドラインのために","Native signals.":"ネイティブな信号。","No dashboard tax.":"ダッシュボード不要。","The nekoHub agent reads Linux directly. Metrics stay lightweight, structured, and available without a permanent SSH polling loop.":"nekoHubエージェントはLinuxを直接読み取ります。常時SSHポーリングなしで軽量なメトリクスを提供します。","Linux-native telemetry":"Linuxネイティブテレメトリ","Local by default":"ローカルが標準","Prometheus ready":"Prometheus対応",
  "A cleaner control loop":"より明快な制御ループ","SSH opens the door.":"SSHが扉を開き、","The agent keeps watch.":"エージェントが見守る。","YOU":"あなた","one keyboard-first workspace":"キーボード中心のワークスペース","SSH · DISCOVER + OPERATE":"SSH · 検出 + 操作","native Linux telemetry":"Linuxネイティブテレメトリ","METRICS · CONTINUOUS":"メトリクス · 継続","EXPORT":"エクスポート","optional, always compatible":"任意、常に互換",
  "Now and next":"現在とこれから","Useful today.":"今日から使える。","Built for the long run.":"長期を見据えた設計。","CURRENT · v0.3.1":"現在 · v0.3.1","Shipping now":"提供中","On the horizon":"今後の予定","Local host monitoring":"ローカルホスト監視","Machine inventory":"マシンインベントリ","Persistent groups":"永続グループ","Prometheus metrics":"Prometheusメトリクス","APT installation":"APTインストール","Secure remote agent pairing":"安全なリモートエージェント接続","Services and logs":"サービスとログ","Custom themes":"カスタムテーマ","Community theme store":"コミュニティテーマストア",
  "Made for people who run things":"運用する人のために","From one quiet homelab to a fleet of restless VPSs.":"静かなホームラボから、動き続けるVPSフリートまで。","Sysadmins":"システム管理者","See every host without leaving the terminal.":"ターミナルを離れずに全ホストを確認。","Homelabbers":"ホームラボユーザー","Keep the lab organized, legible, and fun.":"ラボを整理し、見やすく、楽しく。","Inspect faster and stay compatible with existing observability.":"既存の可観測性を保ちながら素早く調査。","Terminal people":"ターミナル愛好家","Use an interface that respects your keyboard and attention.":"キーボードと集中を尊重するインターフェース。",
  "Up and running":"すぐに始める","One command.":"コマンドひとつ。","Your fleet, in view.":"フリートを一望。","Install the current release from the official APT repository. nekoHub is open source and built in public.":"公式APTリポジトリから最新版をインストール。nekoHubは公開開発されるオープンソースです。","APT repository":"APTリポジトリ","Read the source":"ソースを読む","Copy":"コピー","Copied":"コピーしました","Linux fleet management,":"Linuxフリート管理を、","designed for the terminal.":"ターミナルのために。","Star on GitHub":"GitHubでスター","Back to top ↑":"トップへ戻る ↑",
  "Personalize your terminal":"ターミナルを自分らしく","A theme shop,":"コミュニティが作る、","made by the community.":"テーマショップ。","Discover palettes crafted for long sessions, share your own, and make every fleet feel like home.":"長時間の作業に適した配色を見つけ、自分のテーマを共有し、フリートを心地よい場所に。","COMING SOON":"近日公開","THEME PREVIEW":"テーマプレビュー"
};

Object.assign(pt, {
  "Theme Shop":"Loja de temas",", not like another platform to operate.":", não outra plataforma para administrar.","fleet / overview":"frota / visão geral","live":"ao vivo","GROUPS":"GRUPOS","All machines":"Todas as máquinas","Production":"Produção","QUICK VIEW":"VISÃO RÁPIDA","Alerts":"Alertas","Services":"Serviços","SELECTED HOST":"HOST SELECIONADO","connected":"conectado","MEMORY":"MEMÓRIA","stable":"estável","NETWORK · LAST 60S":"REDE · ÚLTIMOS 60S","TOP PROCESSES":"PROCESSOS PRINCIPAIS","help":"ajuda","groups":"grupos","refresh":"atualizar"
});
Object.assign(ja, {
  "Theme Shop":"テーマショップ",", not like another platform to operate.":"であるべきです。","Direct reads from":"/procと/sysを直接読み取り、","keep the agent transparent and efficient.":"透明で効率的なエージェントを実現します。","A Unix socket keeps host communication close, predictable, and easy to reason about.":"Unixソケットにより、ホストとの通信を近く、予測可能に保ちます。","Use nekoHub's focused TUI and keep the monitoring stack you already trust.":"nekoHubのTUIと、信頼する監視スタックをそのまま使えます。","Discovery and operations still use SSH. Continuous metrics come from a purpose-built agent, so collection remains stable without holding remote sessions open.":"検出と操作にはSSHを使用し、継続的なメトリクスは専用エージェントが収集します。","Native /proc and /sys reads":"/procと/sysのネイティブ読み取り","Docker and Podman":"DockerとPodman","fleet / overview":"フリート / 概要","live":"ライブ","GROUPS":"グループ","All machines":"すべてのマシン","Production":"本番","Homelab":"ホームラボ","QUICK VIEW":"クイックビュー","Alerts":"アラート","Services":"サービス","SELECTED HOST":"選択中のホスト","connected":"接続済み","MEMORY":"メモリ","TEMP":"温度","stable":"安定","NETWORK · LAST 60S":"ネットワーク · 直近60秒","TOP PROCESSES":"上位プロセス","help":"ヘルプ","groups":"グループ","refresh":"更新"
});

Object.assign(pt, {
  "Agent":"Agente","The real application":"O aplicativo de verdade","One TUI.":"Uma TUI.","Every terminal size.":"Em qualquer tamanho de terminal.","The interface follows the real Ratatui layout: cards reorganize as the terminal changes, keeping every action clear from a compact pane to a full-screen session.":"A interface segue o layout real em Ratatui: os cards se reorganizam conforme o terminal muda, mantendo tudo claro de um painel compacto à tela cheia.","Resize the terminal":"Redimensione o terminal","live layout":"layout ao vivo","machines":"máquinas","machine":"máquina","New group":"Novo grupo","Create a machine group":"Criar grupo de máquinas","Enter to add":"Enter para adicionar","group ready":"grupo pronto","nekoHub agent":"agente nekoHub","A quiet Linux service that does one job well.":"Um serviço Linux discreto que faz uma coisa muito bem.","It reads native system signals, keeps a short local history, and serves the TUI without root privileges. No permanent SSH polling loop, no heavy runtime.":"Ele lê sinais nativos do sistema, mantém um breve histórico local e atende a TUI sem privilégios root. Sem consultas SSH permanentes e sem runtime pesado.","Explore the agent source":"Explorar o código do agente","active (running)":"ativo (em execução)","CPU · memory · disk · load · network":"CPU · memória · disco · carga · rede","read-only · no root · 1 second samples":"somente leitura · sem root · amostras a cada 1 segundo","Prometheus compatible · optional by design":"compatível com Prometheus · opcional por design"
});
Object.assign(ja, {
  "Agent":"エージェント","The real application":"実際のアプリ","One TUI.":"ひとつのTUI。","Every terminal size.":"あらゆるターミナルサイズに。","The interface follows the real Ratatui layout: cards reorganize as the terminal changes, keeping every action clear from a compact pane to a full-screen session.":"実際のRatatuiレイアウトに基づき、ターミナルの大きさに合わせてカードが再配置されます。","Resize the terminal":"ターミナルをリサイズ","live layout":"ライブレイアウト","machines":"マシン","machine":"マシン","New group":"新しいグループ","Create a machine group":"マシングループを作成","Enter to add":"Enterで追加","group ready":"グループ準備完了","nekoHub agent":"nekoHubエージェント","A quiet Linux service that does one job well.":"ひとつの仕事を確実にこなす静かなLinuxサービス。","It reads native system signals, keeps a short local history, and serves the TUI without root privileges. No permanent SSH polling loop, no heavy runtime.":"システムのネイティブ情報を読み取り、短いローカル履歴を保持し、root権限なしでTUIに提供します。","Explore the agent source":"エージェントのソースを見る","active (running)":"稼働中","CPU · memory · disk · load · network":"CPU · メモリ · ディスク · 負荷 · ネットワーク","read-only · no root · 1 second samples":"読み取り専用 · root不要 · 1秒ごとに取得","Prometheus compatible · optional by design":"Prometheus互換 · 必要なときだけ"
});

const originals = new WeakMap();
export const languageLabels = { en:"English", pt:"Português", ja:"日本語" };
export function translatePage(root, locale){
  if(!root) return; const table=locale==="pt"?pt:locale==="ja"?ja:null;
  const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);
  while(walker.nextNode()){
    const node=walker.currentNode; if(node.parentElement?.closest("[data-no-translate]")) continue; if(!originals.has(node)) originals.set(node,node.nodeValue);
    const original=originals.get(node), key=original.trim();
    if(!key) continue; const value=table?.[key] ?? key;
    node.nodeValue=original.replace(key,value);
  }
}
